<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class KeywordSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        $keywords = [

            'Abundance',
            'Adaptation',
            'Ancestors',
            'Anxiety',
            'Arrogance',
            'Arts',
            'Bad luck',
            'Balance',
            'Beauty',
            'Beginning',
            'Birth',
            'Challenges',
            'Chaos',
            'Cleansing',
            'Command',
            'Communication',
            'Compassion',
            'Completion',
            'Connection with the divine',
            'Connection',
            'Consciousness',
            'Courage',
            'Craftsmanship',
            'Creation',
            'Creativity',
            'Cultivation',
            'Cycles',
            'Death',
            'Destruction',
            'Dignity',
            'Direction',
            'Discipline',
            'Discord',
            'Divination',
            'Divine spark',
            'Dream',
            'Ego',
            'Energy',
            'Enlightenment',
            'Equality',
            'Fears',
            'Firmness',
            'Flexibility',
            'Forge',
            'Freedom',
            'Frenzy',
            'Friendship',
            'Good health',
            'Guidance',
            'Grief',
            'Growth',
            'Healing',
            'History',
            'Honor',
            'Imprudence',
            'Impulsivity',
            'Initiation',
            'Inspiration',
            'Instability',
            'Integrity',
            'Intensity',
            'Intention',
            'Intuition',
            'Invocation',
            'Joy',
            'Justice',
            'Kindness',
            'Knowledge',
            'Law',
            'Leadership',
            'Legacy',
            'Liberation',
            'Longevity',
            'Love',
            'Loyalty',
            'Magic',
            'Magical attack',
            'Masculinity',
            'Mastery',
            'Memory',
            'Mirror',
            'Movement',
            'Mysticism',
            'Necromancy',
            'Oath',
            'Order',
            'Passion',
            'Patience',
            'Peace',
            'Perseverance',
            'Pleasures',
            'Poetry',
            'Power',
            'Pride',
            'Prophecy',
            'Prosperity',
            'Protection',
            'Prudence',
            'Purification',
            'Raw emotions',
            'Regeneration',
            'Resilience',
            'Resistance',
            'Respect',
            'Responsibility',
            'Rest',
            'Revelation',
            'Roots',
            'Royalty',
            'Self-expression',
            'Sexuality',
            'Shape-shifting',
            'Shelter',
            'Skill',
            'Sovereignty',
            'Speed',
            'Stability',
            'Strategy',
            'Strength',
            'Talent',
            'Teaching',
            'Tenderness',
            'Threshold',
            'Tradition',
            'Transcendence',
            'Transformation',
            'Transmission',
            'Travel',
            'Trust',
            'Truth',
            'Uncertainty',
            'Underworld',
            'Victory',
            'Violence',
            'Vision',
            'Voice',
            'Wealth',
            'Weaving',
            'Well-being',
            'Wheel',
            'Wisdom',
            'Wound'
        ];

        foreach ($keywords as $keyword) {
            DB::table('keywords')->insert([
                'name' => $keyword,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
