<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Keyword>
 */
class KeywordFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'name' => 'Abundance',
            'name' => 'Adaptation',
            'name' => 'Ancestors',
            'name' => 'Anxiety',
            'name' => 'Arrogance',
            'name' => 'Arts',
            'name' => 'Bad luck',
            'name' => 'Balance',
            'name' => 'Beauty',
            'name' => 'Beginning',
            'name' => 'Birth',
            'name' => 'Challenges',
            'name' => 'Chaos',
            'name' => 'Cleansing',
            'name' => 'Command',
            'name' => 'Communication',
            'name' => 'Compassion',
            'name' => 'Completion',
            'name' => 'Connection',
            'name' => 'Connection with the divine',
            'name' => 'Consciousness',
            'name' => 'Courage',
            'name' => 'Craftsmanship',
            'name' => 'Creation',
            'name' => 'Creativity',
            'name' => 'Cultivation',
            'name' => 'Cycles',
            'name' => 'Death',
            'name' => 'Destruction',
            'name' => 'Dignity',
            'name' => 'Direction',
            'name' => 'Discipline',
            'name' => 'Discord',
            'name' => 'Divination',
            'name' => 'Divine spark',
            'name' => 'Dream',
            'name' => 'Ego',
            'name' => 'Energy',
            'name' => 'Enlightenment',
            'name' => 'Equality',
            'name' => 'Fears',
            'name' => 'Firmness',
            'name' => 'Flexibility',
            'name' => 'Forge',
            'name' => 'Freedom',
            'name' => 'Frenzy',
            'name' => 'Friendship',
            'name' => 'Good health',
            'name' => 'Grief',
            'name' => 'Growth',
            'name' => 'Healing',
            'name' => 'History',
            'name' => 'Honor',
            'name' => 'Imprudence',
            'name' => 'Impulsivity',
            'name' => 'Initiation',
            'name' => 'Inspiration',
            'name' => 'Instability',
            'name' => 'Integrity',
            'name' => 'Intensity',
            'name' => 'Intention',
            'name' => 'Intuition',
            'name' => 'Invocation',
            'name' => 'Joy',
            'name' => 'Justice',
            'name' => 'Kindness',
            'name' => 'Knowledge',
            'name' => 'Law',
            'name' => 'Leadership',
            'name' => 'Legacy',
            'name' => 'Liberation',
            'name' => 'Longevity',
            'name' => 'Love',
            'name' => 'Loyalty',
            'name' => 'Magic',
            'name' => 'Magical attack',
            'name' => 'Masculinity',
            'name' => 'Mastery',
            'name' => 'Memory',
            'name' => 'Mirror',
            'name' => 'Movement',
            'name' => 'Mysticism',
            'name' => 'Necromancy',
            'name' => 'Oath',
            'name' => 'Order',
            'name' => 'Passion',
            'name' => 'Patience',
            'name' => 'Peace',
            'name' => 'Perseverance',
            'name' => 'Pleasures',
            'name' => 'Poetry',
            'name' => 'Power',
            'name' => 'Pride',
            'name' => 'Prophecy',
            'name' => 'Prosperity',
            'name' => 'Protection',
            'name' => 'Prudence',
            'name' => 'Purification',
            'name' => 'Raw emotions',
            'name' => 'Regeneration',
            'name' => 'Resilience',
            'name' => 'Resistance',
            'name' => 'Respect',
            'name' => 'Responsibility',
            'name' => 'Rest',
            'name' => 'Revelation',
            'name' => 'Roots',
            'name' => 'Royalty',
            'name' => 'Self-expression',
            'name' => 'Sexuality',
            'name' => 'Shape-shifting',
            'name' => 'Shelter',
            'name' => 'Skill',
            'name' => 'Sovereignty',
            'name' => 'Speed',
            'name' => 'Stability',
            'name' => 'Strategy',
            'name' => 'Strength',
            'name' => 'Talent',
            'name' => 'Tenderness',
            'name' => 'Threshold',
            'name' => 'Tradition',
            'name' => 'Transcendence',
            'name' => 'Transformation',
            'name' => 'Transmission',
            'name' => 'Travel',
            'name' => 'Trust',
            'name' => 'Truth',
            'name' => 'Uncertainty',
            'name' => 'Underworld',
            'name' => 'Victory',
            'name' => 'Violence',
            'name' => 'Vision',
            'name' => 'Voice',
            'name' => 'Wealth',
            'name' => 'Weaving',
            'name' => 'Well-being',
            'name' => 'Wheel',
            'name' => 'Wisdom',
            'name' => 'Wound'
        ];
    }
}
