INSERT INTO `constellations` (`constellation`, `abbrev`, `id`) VALUES
('Andromeda', 'And', 1),
('Antlia', 'Ant', 2),
('Apus', 'Aps', 3),
('Aquarius', 'Aqr', 4),
('Aquila', 'Aql', 5),
('Ara', 'Ara', 6),
('Aries', 'Ari', 7),
('Auriga', 'Aur', 8),
('Bootes', 'Boo', 9),
('Caelum', 'Cae', 10),
('Camelopardalis', 'Cam', 11),
('Cancer', 'Cnc', 12),
('Canes Venatici', 'CVn', 13),
('Canis Major', 'CMa', 14),
('Canis Minor', 'CMi', 15),
('Capricornus', 'Cap', 16),
('Carina', 'Car', 17),
('Cassiopeia', 'Cas', 18),
('Centaurus', 'Cen', 19),
('Cepheus', 'Cep', 20),
('Cetus', 'Cet', 21),
('Chamaeleon', 'Cha', 22),
('Circinus', 'Cir', 23),
('Columba', 'Col', 24),
('Coma Berenices', 'Com', 25),
('Corona Australis', 'CrA', 26),
('Corona Borealis', 'CrB', 27),
('Corvus', 'Crv', 28),
('Crater', 'Crt', 29),
('Crux', 'Cru', 30),
('Cygnus', 'Cyg', 31),
('Delphinus', 'Del', 32),
('Dorado', 'Dor', 33),
('Draco', 'Dra', 34),
('Equuleus', 'Equ', 35),
('Eridanus', 'Eri', 36),
('Fornax', 'For', 37),
('Gemini', 'Gem', 38),
('Grus', 'Gru', 39),
('Hercules', 'Her', 40),
('Horologium', 'Hor', 41),
('Hydra', 'Hya', 42),
('Hydrus', 'Hyi', 43),
('Indus', 'Ind', 44),
('Lacerta', 'Lac', 45),
('Leo', 'Leo', 46),
('Leo Minor', 'LMi', 47),
('Lepus', 'Lep', 48),
('Libra', 'Lib', 49),
('Lupus', 'Lup', 50),
('Lynx', 'Lyn', 51),
('Lyra', 'Lyr', 52),
('Mensa', 'Men', 53),
('Microscopium', 'Mic', 54),
('Monoceros', 'Mon', 55),
('Musca', 'Mus', 56),
('Norma', 'Nor', 57),
('Octans', 'Oct', 58),
('Ophiuchus', 'Oph', 59),
('Orion', 'Ori', 60),
('Pavo', 'Pav', 61),
('Pegasus', 'Peg', 62),
('Perseus', 'Per', 63),
('Phoenix', 'Phe', 64),
('Pictor', 'Pic', 65),
('Pisces', 'Psc', 66),
('Piscis Austrinus', 'PsA', 67),
('Puppis', 'Pup', 68),
('Pyxis', 'Pyx', 69),
('Reticulum', 'Ret', 70),
('Sagitta', 'Sge', 71),
('Sagittarius', 'Sgr', 72),
('Scorpius', 'Sco', 73),
('Sculptor', 'Scl', 74),
('Scutum', 'Sct', 75),
('Serpens', 'Ser', 76),
('Sextans', 'Sex', 77),
('Taurus', 'Tau', 78),
('Telescopium', 'Tel', 79),
('Triangulum', 'Tri', 80),
('Triangulum Australe', 'TrA', 81),
('Tucana', 'Tuc', 82),
('Ursa Major', 'UMa', 83),
('Ursa Minor', 'UMi', 84),
('Vela', 'Vel', 85),
('Virgo', 'Vir', 86),
('Volans', 'Vol', 87),
('Vulpecula', 'Vul', 88);